image: node:14.16.0

build: &build
  step:
    name: Build
    script:
      - yarn install -D --network-concurrency 1
      - yarn build
    artifacts:
      - dist/**
    caches:
      - node

test: &test
  step:
    name: Unit Test
    script:
      - yarn install -D --network-concurrency 1
      - ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
      - JEST_JUNIT_OUTPUT_DIR="$(pwd)/test-results" yarn test --ci --reporters=default --reporters=jest-junit
    caches:
      - node
      - jest

coverage: &coverage
  step:
    name: Unit Test Coverage
    script:
      - yarn install -D --network-concurrency 1
      - ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
      - yarn test --coverage --ci
    caches:
      - node
      - jest

lint: &lint
  step:
    name: Lint
    script:
      - yarn install -D --network-concurrency 1
      - yarn lint --quiet
    caches:
      - node

securityScan: &securityScan
  step:
    name: Security Scan
    script:
      - pipe: atlassian/git-secrets-scan:0.4.3

deploy: &deploy
  step:
    name: Deploy to Production
    deployment: Production
    script:
      - npm --no-git-tag-version version "1.0.$BITBUCKET_BUILD_NUMBER" -m "Upgrade to new version"
      - pipe: atlassian/npm-publish:0.3.1
        variables:
          NPM_TOKEN: $TREESTONE_NPM_TOKEN

pipelines:
  default:
    - <<: *build
    - parallel:
        - <<: *test
        - <<: *coverage
        - <<: *lint

  branches:
    master:
      - <<: *build
      - parallel:
          - <<: *test
          - <<: *coverage
          - <<: *lint
          - <<: *securityScan
      - <<: *deploy

definitions:
  caches:
    jest: ./.ci/jest_cache
